[metadata]
name = inv3D-generator
version = 0.0.1
author = Felix Hertlein
author_email = hertlein@fzi.de
description = Inv3D dataset generator
long_description = file: README.md
long_description_content_type = text/markdown
classifiers =
    Programming Language :: Python :: 3

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.8
install_requires =
    numpy
    tqdm
    dpath
    pandas
    phonenumbers
    Fake
    schwifty
    opencv_python
    bounding_box
    scikit_learn
    beautifulsoup4
    pdf2image
    selenium
    webdriver_manager
    pdfminer
    torch
    Flask
    Werkzeug

[options.packages.find]
where = src
